# Generated by Django 4.1.4 on 2023-04-10 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='course',
            new_name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.department'),
        ),
    ]
