# Generated by Django 4.1.4 on 2023-04-10 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_rename_course_department_courses_course_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='courses',
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.department'),
        ),
    ]
