# Generated by Django 4.1.4 on 2023-04-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_department_wiki_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='wiki_add',
            field=models.URLField(max_length=300),
        ),
    ]
